"""User-level startup service installation and detached execution."""

import os
import plistlib
import subprocess
import sys
from pathlib import Path
from typing import Sequence

from ai_usage.settings import Paths

SERVICE_MARKER = "Generated by ai-usage"


def service_arguments(enable_server: bool, host: str, port: int) -> list[str]:
    if enable_server:
        return ["up", "--host", host, "--port", str(port)]
    # end if
    return ["crawl"]
# end def


def systemd_unit(executable: str, arguments: Sequence[str]) -> str:
    command = " ".join([executable, *arguments])
    return f"""# {SERVICE_MARKER}
[Unit]
Description=AI usage crawler
After=network-online.target

[Service]
Type=simple
ExecStart={command}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
"""
# end def


def launchd_plist(executable: str, arguments: Sequence[str], paths: Paths) -> bytes:
    payload = {
        "Label": "com.ai-usage.crawler",
        "ProgramArguments": [executable, *arguments],
        "RunAtLoad": True,
        "KeepAlive": True,
        "StandardOutPath": str(paths.logs / "service.log"),
        "StandardErrorPath": str(paths.logs / "service-error.log"),
        "AIUsageMarker": SERVICE_MARKER,
    }
    return plistlib.dumps(payload)
# end def


def install_service(paths: Paths, enable_server: bool, host: str, port: int) -> Path:
    arguments = service_arguments(enable_server, host, port)
    executable = str(Path(sys.executable).parent / "ai-usage")
    if sys.platform.startswith("linux"):
        target = Path.home() / ".config" / "systemd" / "user" / "ai-usage.service"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(systemd_unit(executable, arguments), encoding="utf-8")
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "--user", "enable", "--now", target.name], check=True)
    elif sys.platform == "darwin":
        target = Path.home() / "Library" / "LaunchAgents" / "com.ai-usage.crawler.plist"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(launchd_plist(executable, arguments, paths))
        subprocess.run(["launchctl", "bootstrap", f"gui/{os.getuid()}", str(target)], check=True)
    elif sys.platform == "win32":
        target = paths.local / "ai-usage-task.txt"
        command = " ".join([executable, *arguments])
        subprocess.run(
            ["schtasks", "/Create", "/F", "/SC", "ONLOGON", "/TN", "AI Usage", "/TR", command],
            check=True,
        )
        target.write_text(SERVICE_MARKER, encoding="utf-8")
    else:
        raise RuntimeError(f"startup installation is unsupported on {sys.platform}")
    # end if
    return target
# end def


def uninstall_service(paths: Paths) -> None:
    if sys.platform.startswith("linux"):
        target = Path.home() / ".config" / "systemd" / "user" / "ai-usage.service"
        if target.exists() and SERVICE_MARKER in target.read_text(encoding="utf-8"):
            subprocess.run(["systemctl", "--user", "disable", "--now", target.name], check=False)
            target.unlink()
            subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
        # end if
    elif sys.platform == "darwin":
        target = Path.home() / "Library" / "LaunchAgents" / "com.ai-usage.crawler.plist"
        if target.exists() and SERVICE_MARKER in target.read_text(encoding="utf-8", errors="ignore"):
            subprocess.run(["launchctl", "bootout", f"gui/{os.getuid()}", str(target)], check=False)
            target.unlink()
        # end if
    elif sys.platform == "win32":
        subprocess.run(["schtasks", "/Delete", "/F", "/TN", "AI Usage"], check=False)
        target = paths.local / "ai-usage-task.txt"
        if target.exists():
            target.unlink()
        # end if
    # end if
# end def


def detach(arguments: Sequence[str], paths: Paths) -> int:
    paths.ensure()
    log_path = paths.logs / "detached.log"
    with log_path.open("ab") as stream:
        process = subprocess.Popen(
            [sys.executable, "-m", "ai_usage", *arguments],
            stdin=subprocess.DEVNULL,
            stdout=stream,
            stderr=stream,
            start_new_session=sys.platform != "win32",
            creationflags=subprocess.DETACHED_PROCESS if sys.platform == "win32" else 0,
        )
    # end with
    (paths.local / "ai-usage.pid").write_text(f"{process.pid}\n", encoding="utf-8")
    return process.pid
# end def

