"""User-level and Docker service management."""

import subprocess
import sys
from pathlib import Path
from typing import Sequence

from ai_usage.services.base import ServiceMode, ServiceStatus, service_arguments
from ai_usage.settings import Paths

SERVICE_MARKER = "Generated by ai-usage"


def executable() -> str:
    return str(Path(sys.executable).parent / "ai-usage")
# end def


def local_install(paths: Paths, mode: ServiceMode, host: str, port: int) -> Path:
    arguments = service_arguments(mode, host, port)
    if sys.platform.startswith("linux"):
        from ai_usage.services import linux

        return linux.install(executable(), arguments)
    # end if
    if sys.platform == "darwin":
        from ai_usage.services import macos

        return macos.install(executable(), arguments, paths.logs)
    # end if
    if sys.platform == "win32":
        from ai_usage.services import windows

        return windows.install(executable(), arguments, paths.local)
    # end if
    raise RuntimeError(f"startup installation is unsupported on {sys.platform}")
# end def


def local_status(paths: Paths) -> ServiceStatus:
    if sys.platform.startswith("linux"):
        from ai_usage.services import linux

        return linux.status()
    # end if
    if sys.platform == "darwin":
        from ai_usage.services import macos

        return macos.status()
    # end if
    if sys.platform == "win32":
        from ai_usage.services import windows

        return windows.status(paths.local)
    # end if
    raise RuntimeError(f"startup installation is unsupported on {sys.platform}")
# end def


def local_uninstall(paths: Paths) -> None:
    if sys.platform.startswith("linux"):
        from ai_usage.services import linux

        linux.uninstall()
    elif sys.platform == "darwin":
        from ai_usage.services import macos

        macos.uninstall()
    elif sys.platform == "win32":
        from ai_usage.services import windows

        windows.uninstall(paths.local)
    else:
        raise RuntimeError(f"startup installation is unsupported on {sys.platform}")
    # end if
# end def


def detach(arguments: Sequence[str], paths: Paths) -> int:
    paths.ensure()
    log_path = paths.logs / "detached.log"
    with log_path.open("ab") as stream:
        process = subprocess.Popen([sys.executable, "-m", "ai_usage", *arguments], stdin=subprocess.DEVNULL, stdout=stream, stderr=stream, start_new_session=sys.platform != "win32", creationflags=subprocess.DETACHED_PROCESS if sys.platform == "win32" else 0)
    # end with
    (paths.local / "ai-usage.pid").write_text(f"{process.pid}\n", encoding="utf-8")
    return process.pid
# end def
