"""systemd user-service integration."""

import os
import subprocess
from pathlib import Path
from typing import Sequence

from ai_usage.services.base import ServiceMode, ServiceStatus

SERVICE_MARKER = "Generated by ai-usage"
SERVICE_NAME = "ai-usage.service"


def target_path() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd" / "user" / SERVICE_NAME
# end def


def unit(executable: str, arguments: Sequence[str]) -> str:
    return f"""# {SERVICE_MARKER}
[Unit]
Description=AI Usage service
After=network-online.target

[Service]
Type=simple
ExecStart={' '.join([executable, *arguments])}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
"""
# end def


def install(executable: str, arguments: Sequence[str]) -> Path:
    target = target_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(unit(executable, arguments), encoding="utf-8")
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", "--now", SERVICE_NAME], check=True)
    return target
# end def


def status() -> ServiceStatus:
    target = target_path()
    if not target.exists() or SERVICE_MARKER not in target.read_text(encoding="utf-8"):
        return ServiceStatus(False, None, None, None, "not installed")
    # end if
    enabled = subprocess.run(["systemctl", "--user", "is-enabled", SERVICE_NAME], capture_output=True).returncode == 0
    active = subprocess.run(["systemctl", "--user", "is-active", SERVICE_NAME], capture_output=True).returncode == 0
    command = target.read_text(encoding="utf-8")
    mode: ServiceMode = "both" if " up " in command else "webserver" if " serve " in command else "crawler"
    return ServiceStatus(True, enabled, active, mode, str(target))
# end def


def uninstall() -> None:
    target = target_path()
    if target.exists() and SERVICE_MARKER in target.read_text(encoding="utf-8"):
        subprocess.run(["systemctl", "--user", "disable", "--now", SERVICE_NAME], check=False)
        target.unlink()
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    # end if
# end def
